#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "withings-sync"
name = "Withings Sync"
description.en = "A tool for synchronisation of the Withings API to Garmin Connect and Trainer Road"

version = "4.2.7~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
code = "https://github.com/jaroslawhartman/withings-sync"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.garmin_username]
    ask.en = "What’s your Garmin Connect username?"
    type = "string"
    optional = true

    [install.garmin_password]
    ask.en = "What’s the Garmin Connect password?"
    type = "password"
    optional = true

    [install.trainerroad_username]
    ask.en = "What’s your Trainer Road username?"
    type = "string"
    optional = true

    [install.trainerroad_password]
    ask.en = "What’s the Trainer Road password?"
    type = "password"
    optional = true

[resources]

    [resources.sources]
   
    [resources.system_user]

    [resources.install_dir]

    [resources.apt]
    packages = "python3, python3-venv"

