#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Not saved by default
ynh_app_setting_set --key=password --value="$password"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install withings-sync=="$(ynh_app_upstream_version)"

    ynh_safe_rm "$install_dir/.cache/pip"
popd

#=================================================
# INITIALIZE APP
#=================================================
 ynh_script_progression "Initialize $app..."

set -a

source $install_dir/.env

ynh_hide_warnings $install_dir/venv/bin/withings-sync

set +a

#=================================================
# ADD A CRON JOB
#=================================================
ynh_config_add --template="withings-sync.cron" --destination="/etc/cron.d/$app"

chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_logrotate
touch /var/log/"$app"/"$app".log
chown -R "$app":"$app" /var/log/"$app"/

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
